# -*- coding: utf-8 -*-
"""Nitrogen Consumption

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCR_FsRO6VktJAk3lRlRf6OodcQMmS8m

#Nitrogen Project

## SETUP Everything
"""

#setup
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

# Load Abalone Shell Data
NitrogenFoods = pd.read_csv('/content/drive/MyDrive/Nitrogen Stuff/Data/Crop_recommendation.csv', header=None)
names = ['N', 'P', 'K', 'temperature', 'humidity', 'ph',
         'rainfall', 'label']

NitrogenFoods.columns=names
NitrogenFoods.head()

"""Setup Values"""

#view
NitrogenFoods = pd.read_csv("/content/drive/MyDrive/Nitrogen Stuff/Data/Crop_recommendation.csv")
NitrogenFoods.head()
import matplotlib.pyplot as plt
#add nice background (gray with white grid)
import seaborn as sns
sns.set()

#change size
plt.figure(figsize = (10, 6))

#show histogram G1 column
plt.hist(NitrogenFoods["N"], color= "skyblue", alpha= 0.7)

plt.xlabel("Nitrogen")

plt.ylabel("Count")

title = "Nitrogen Levels"

plt.title(title)

plt.savefig(title, dpi=200)

plt.show

#view
NitrogenFoods = pd.read_csv("/content/drive/MyDrive/Nitrogen Stuff/Data/Crop_recommendation.csv")
NitrogenFoods.head()
import matplotlib.pyplot as plt
#add nice background (gray with white grid)
import seaborn as sns
sns.set()

#change size
plt.figure(figsize = (50, 15))

#show histogram G1 column
plt.hist(NitrogenFoods["label"], color= "skyblue", alpha= 0.7)

plt.xlabel("Common Foods")

plt.ylabel("Count")

title = "Most Common Nitrogen Levels Found in Food"

plt.title(title)

plt.savefig(title, dpi=200)

plt.show

"""Looking at How Many Ingredients There Are:"""

NitrogenFoods['label'].describe()

NitrogenFoods['label'].unique()

"""## Start Some Grphs"""

#Nitrogen Food Graph

import seaborn as sns
import matplotlib.pyplot as plt

sns.set()

plot_order = NitrogenFoods.sort_values(by='N', ascending=False).values
plt.plot
#sns.lineplot()
#sns.regplot(x=NitrogenFoods['lable'], y=NitrogenFoods['N'])
plt.figure(figsize=(100, 10))
sns.pointplot(x=NitrogenFoods['N'], y=NitrogenFoods['ph'], #hue=NitrogenFoods['K'],
              sizes=(20, 600), palette=('winter_r'))

title = 'pH levels as Nitrogen Count Increases'
plt.title(title)

plt.savefig(title, dpi=250)
plt.show()

#Nitrogen Food Graph

import seaborn as sns
import matplotlib.pyplot as plt

sns.set()

plot_order = NitrogenFoods.sort_values(by='N', ascending=False).values
plt.plot
#sns.lineplot()
#sns.regplot(x=NitrogenFoods['lable'], y=NitrogenFoods['N'])
plt.figure(figsize=(100, 25))
sns.pointplot(x=NitrogenFoods['N'], y=NitrogenFoods['ph'], hue=NitrogenFoods['K'],
              sizes=(20, 600), palette=('winter_r'))

title = 'pH levels as Nitrogen Count Increases with Potassium'
plt.title(title)

plt.savefig(title, dpi=250)
plt.show()

#Nitrogen Food Graph

import seaborn as sns
import matplotlib.pyplot as plt

sns.set()

plot_order = NitrogenFoods.sort_values(by='N', ascending=False).values
plt.plot
#sns.lineplot()
#sns.regplot(x=NitrogenFoods['lable'], y=NitrogenFoods['N'])
plt.figure(figsize=(45, 10))
sns.pointplot(x=NitrogenFoods['label'], y=NitrogenFoods['N'],
              sizes=(20, 600), palette=('winter_r'))

title = 'Common Ingredients Scaled Against Nitrogen Count'
plt.title(title)

plt.savefig(title, dpi=250)
plt.show()

"""## Setup For Common Foods"""

# Load Abalone Shell Data
NitrogenFoods = pd.read_csv('/content/drive/MyDrive/Nitrogen Stuff/Data/Nitrogen in Common Foods.csv', header=None)
names = ['Food', 'Nitrogen Content', ' ']

NitrogenFoods.columns=names
NitrogenFoods.head()

"""turning the values into non-null

see how many common foods we are using
"""

NitrogenFoods['Food'].describe()

NitrogenFoods['Food'].unique()

#view for nitrogen content (in grams)
NitrogenFoods = pd.read_csv("/content/drive/MyDrive/Nitrogen Stuff/Data/Nitrogen in Common Foods.csv")
NitrogenFoods.head()

#add nice background (gray with white grid)
import seaborn as sns
sns.set()

#change size
plt.figure(figsize = (10, 6))

#show histogram G1 column
plt.hist(NitrogenFoods["Nitrogen Content"], color= "skyblue", alpha= 0.7)

plt.xlabel("Nitrogen Amount (g)")

plt.ylabel("Count")

title = "Nitrogen Count"

plt.title(title)

plt.savefig(title, dpi=200)

plt.show

"""Plot Graph"""

#Nitrogen Food Graph

import seaborn as sns
import matplotlib.pyplot as plt

sns.set()

plot_order = NitrogenFoods.sort_values(by='Nitrogen Content', ascending=False).values
plt.plot
#sns.lineplot()
#sns.regplot(x=NitrogenFoods['lable'], y=NitrogenFoods['N'])
plt.figure(figsize=(85, 10))
sns.pointplot(x=NitrogenFoods['Food'], y=NitrogenFoods['Nitrogen Content'],
              sizes=(20, 600), palette=('winter_r'))

title = 'Common Foods Scaled Against Nitrogen Count'
plt.title(title)

plt.savefig(title, dpi=250)
plt.show()

"""Try Bar Graph"""

import seaborn as sns
import matplotlib.pyplot as plt
NitrogenFoods = pd.read_csv("/content/drive/MyDrive/Nitrogen Stuff/Data/Nitrogen in Common Foods.csv")
NitrogenFoods.head()
plt.subplots(figsize=(85, 10))
sns.barplot(data=NitrogenFoods, x='Food', y='Nitrogen Content')

# Importing libraries
import seaborn as sns
import matplotlib.pyplot as plt
NitrogenFoods = pd.read_csv("/content/drive/MyDrive/Nitrogen Stuff/Data/Nitrogen in Common Foods.csv")
NitrogenFoods.head()

# Setting the data
x = NitrogenFoods['Food']
y = NitrogenFoods['Nitrogen Content']

# setting the dimensions of the plot
fig, ax = plt.subplots(figsize=(85, 10))

# drawing the plot
sns.barplot(x, y, ax=ax)
title = 'Common Foods Scaled Against Nitrogen Count Bar Graph'
plt.title(title)

plt.savefig(title, dpi=250)
plt.show()

"""## Now add Countries"""

# Load Abalone Shell Data
NitrogenFoods = pd.read_csv('/content/drive/MyDrive/Nitrogen Stuff/Data/Nitrogen in Common Foods with Countries.csv', header=None)
names = ['Food', 'Nitrogen Content', 'Country']

NitrogenFoods.columns=names
NitrogenFoods.head()

NitrogenFoods['Country'].describe()

NitrogenFoods['Country'].unique()

"""try bar graph"""

import seaborn as sns
import matplotlib.pyplot as plt
NitrogenFoods = pd.read_csv("/content/drive/MyDrive/Nitrogen Stuff/Data/Nitrogen in Common Foods with Countries.csv")
NitrogenFoods.head()
plt.subplots(figsize=(85, 10), dpi=(300))
sns.barplot(data=NitrogenFoods, x='Food', y='Nitrogen Content', hue='Country')

"""## Malnutrition"""

# Load Abalone Shell Data
import pandas as pd
NitrogenFoods = pd.read_csv('/content/drive/MyDrive/Nitrogen Stuff/Data/country-wise-average.csv', header=None)
names = ['Country', 'Income Classification', 'Severe Wasting', 'Wasting', 'Overwight', 'Stunting', 'Underweight', 'U5 Population']

NitrogenFoods.columns=names
NitrogenFoods.head()

#view for nitrogen content (in grams)
NitrogenFoods = pd.read_csv("/content/drive/MyDrive/Nitrogen Stuff/Data/country-wise-average.csv")
NitrogenFoods.head()

#add nice background (gray with white grid)
import seaborn as sns
import matplotlib.pyplot as plt
sns.set()

#change size
plt.figure(figsize = (10, 6))

#show histogram G1 column
plt.hist(NitrogenFoods["Stunting"], color= "skyblue", alpha= 0.7)

plt.xlabel("Stunting %")

plt.ylabel("Count")

title = "Stunting% Count"

plt.title(title)

plt.savefig(title, dpi=200)

plt.show

#view for nitrogen content (in grams)
NitrogenFoods = pd.read_csv("/content/drive/MyDrive/Nitrogen Stuff/Data/country-wise-average.csv")
NitrogenFoods.head()

#add nice background (gray with white grid)
import seaborn as sns
import matplotlib.pyplot as plt
sns.set()

#change size
plt.figure(figsize = (10, 6))

#show histogram G1 column
plt.hist(NitrogenFoods["Underweight"], color= "skyblue", alpha= 0.7)

plt.xlabel("Underweight %")

plt.ylabel("Count")

title = "Underweight% Count"

plt.title(title)

plt.savefig(title, dpi=200)

plt.show

#view for nitrogen content (in grams)
NitrogenFoods = pd.read_csv("/content/drive/MyDrive/Nitrogen Stuff/Data/country-wise-average.csv")
NitrogenFoods.head()

#add nice background (gray with white grid)
import seaborn as sns
import matplotlib.pyplot as plt
sns.set()

#change size
plt.figure(figsize = (10, 6))

#show histogram G1 column
plt.hist(NitrogenFoods["Overweight"], color= "skyblue", alpha= 0.7)

plt.xlabel("Overweight %")

plt.ylabel("Count")

title = "Overweight% Count"

plt.title(title)

plt.savefig(title, dpi=200)

plt.show

"""#**Want more?**

Entire presentation: https://docs.google.com/presentation/d/1XTin5aYf9K7aCtcLcOpgX0-W0X0F-0PyQTPM0xbbAWI/edit?usp=sharing
"""